[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "neuroCLI"
version = "0.1.0"
dependencies = [
    "click",
]

[project.scripts]
neurocli = "neuroCLI.cli:cli"